server:
  port: 8091

spring:
  application:
    name: blog-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: http://localhost:8080
        port: 8791

    management:
      endpoints:
        web:
          exposure:
            include: '*'