server:
  port: 8090

spring:
  application:
    name: base-image

  mvc:
    static-path-pattern=/public/*:

  resources:
    static-locations:
      - file:${upload-path}
upload-path: D:/public/
upload-ip: localhost
