server:
  port: 80

spring:
  application:
    name: blog

  cloud:
    gateway:
      routes:
        - id: baidu
          uri: https://example.org
          predicates:
            - Path=/red
        - id: consumer
          uri: http://localhost:8070/demo/1
          predicates:
            - Before=2021-01-20T17:42:47.789-07:00[America/Denver]
            - Path=/demo/{string}
        - id: blog
          uri: http://localhost:8091/blog/{string}
          predicates:
            - Path=/blog/{string}