server:
  port: 8081

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:mysql://154.8.146.181:3306/blog?characterEncoding=UTF8
    username: root
    password: zxcv1234
    platform: mysql

  application:
    name: base-provider

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 154.8.146.181:8848
