server:
  port: 8082

spring:
  application:
    name: blog-provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:mysql://154.8.146.181:3306/blog?characterEncoding=UTF8
    username: root
    password: zxcv1234
    platform: mysql

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 154.8.146.181:8848
#    sentinel:
#      transport:
#        dashboard: http://154.8.146.181:8080
#        port: 8791
#        clientIp: 192.168.2.120

  mvc:
    static-path-pattern=/static/*:

management:
  endpoints:
    web:
      exposure:
        include: '*'