server:
  port: 8082

spring:
  application:
    name: blog-provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:mysql://154.8.146.181:3306/blog?characterEncoding=UTF8
    username: root
    password: root
    platform: mysql