http:
  port: 80
#https端口号.
server:
  port: 443
  #证书的路径.
  ssl:
    key-store: classpath:dazhi123.top.jks
    #证书密码，请修改为您自己证书的密码.
    key-store-password: zxcv1234
    #秘钥库类型
    keyStoreType: JKS
    #证书别名
#    keyAlias: 大智小站
# keytool -genkey -alias tomcat -dname "CN=Dazhi,OU=大智的小站,O=大智Demo,L=HaiDian,ST=BeiJing,C=CN" -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 365


spring:
  application:
    name: blog-provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: EMBEDDED
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:mysql://154.8.146.181:3306/blog?characterEncoding=UTF8
    username: root
    password: zxcv1234
    platform: mysql

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 154.8.146.181:8848
#    sentinel:
#      transport:
#        dashboard: http://154.8.146.181:8080
#        port: 8791
#        clientIp: 192.168.2.120

  mvc:
    static-path-pattern=/static/*:

management:
  endpoints:
    web:
      exposure:
        include: '*'
